# Generated by Django 6.0.3 on 2026-03-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_At',
            field=models.ImageField(default='images/cricket.jpg', upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
