# Generated by Django 6.0.3 on 2026-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('created_At', models.DateTimeField(auto_now=True)),
                ('updated_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
