# Generated by Django 6.0.3 on 2026-03-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_sociallinks_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'Social Links'},
        ),
    ]
